### ISSUE TITLE
如何使用，双击运行吗？可否支持mac10.11

### ISSUE THREAD

**Issue by mengqutaoyuan** [keepyounger/Json2Property#1]
双击运行就可以吧吗？我电脑10.11.6 文件要求10.12的Mac系统，可否支持10.11的系统？因为目前一些软件不支持10.12 不想升级。感谢分享

**Comment by keepyounger** [comment]
谢谢反馈，已经更新。已经添加安装教程。还有什么不明白的可以@我。

**Comment by mengqutaoyuan** [comment]
好的，thanks

**Comment by mengqutaoyuan** [comment]
@keepyounger 在Mac10.11.6 (15G31)上先运行  扩展，然后执行，sudo /usr/libexec/xpccachectl ，或者先执行sudo /usr/libexec/xpccachectl  再安装扩展，在设置 -> 扩展->全部扩展 中没有Json2Property出现，是否是我操作错误

**Comment by keepyounger** [comment]
@mengqutaoyuan 你先把Xcode 关掉 然后执行 sudo /usr/libexec/xpccachectl 然后再运行Json2Property 然后再去 设置 -> 扩展->全部扩展中看看

**Comment by mengqutaoyuan** [comment]
@keepyounger  xcode完全退出，还是没有显示出

**Comment by keepyounger** [comment]
@mengqutaoyuan 好像在10.11上 xcode 扩展有些问题， 这样吧 你下载下来工程 然后 修改成你自己的签名信息 然后运行工程试试

**Comment by mengqutaoyuan** [comment]
@keepyounger  好的，谢谢。我试一试

**Comment by iHTCboy** [comment]
@keepyounger  今天用公司电脑（10.11.6 (15G1212)）发现也不行，我的电脑10.12没有问题

**Comment by asomeLiao** [comment]
10.12.2 运行部了

**Comment by keepyounger** [comment]
@asameLiao 下载下来源码 自己签名一下
