### ISSUE TITLE
Xcode 8.2.1 没有反应了？

### ISSUE THREAD

**Issue by iHTCboy** [keepyounger/Json2Property#2]
Xcode 8,2,1 没有反应了

**Comment by iHTCboy** [comment]
搞错，json格式有错没有提醒。。

**Comment by keepyounger** [comment]
Xcode8不允许在插件中操作UI层，所以提醒不了，原因是插件无法获取主线程。

**Comment by iHTCboy** [comment]
@keepyounger  好的。明白了，谢谢！

**Comment by keepyounger** [comment]
@iHTCboy 最近发现其实是可以调用UI的，等我加上提示我在告诉你。

**Comment by keepyounger** [comment]
@iHTCboy 最新版本当 json 格式错误的时候。已经加上提示了。

**Comment by iHTCboy** [comment]
@keepyounger 好的，谢谢！！
